[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noises-and-patterns = { path = "../noises-and-patterns" }
png = "0.17.5"
